version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qxx36uajnt43"
s3_prefix = "app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

